pallets/markupsafe

setup.py
"Features" were removed in setuptools 3.0, and the "speedups" feature was removed from markupsafe in #23. Setuptools 3.1 restored "Features" (but they are deprecated), so adding them back here.
Fix #26
=> Restore speedups feature

markupsafe/__init__.py
Added \__version__ attr to package so that scripts that check local
packages to see if newer versions are available can work.
Almost all Python packages have a version attr, and the vast majority of
them name it "\__version__"
=> Add __version__

markupsafe/tests.py
Thanks to a touch of assistance from #pypy, an explicit call to `gc.collect()` will force the objects to be collected rather than letting the runtime defer cleanup to some indeterminate future time.
**Huge warning:** This is *not* guaranteed to continue working in future pypy versions.  Attempting to manipulate the GC is generally an Unwise Thing to Do™, Not Portable Between Runtimes™, and not too dissimilar to direct manipulation of the GIL.  It'll probably be fine, but pypy supports modular GC policies and this has only been tested under the default policy.
=> Explicitly trigger GC prior to counting; fixes #39.

markupsafe/__init__.py, markupsafe/tests.py
I added a failing test. Note that the current implementation deletes the middle portion of the text.
```
======================================================================
FAIL: test_unescape (markupsafe.tests.MarkupTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/nail/home/buck/trees/theirs/markupsafe/markupsafe/tests.py", line 71, in test_unescape
Markup("jack & tavi are cooler than mike &amp; russ").unescape()
AssertionError: jack  russ
----------------------------------------------------------------------
Ran 13 tests in 0.181s
```
Altering the regex fixes this issue.
Secondarily, the current implemetation will delete anything that *looks* like an html entity but is not:
``` …
```
=> idempotent unescape

setup.py
Python.org Python raises a SystemError for a missing compiler when running
"customize_compiler" so before the "build_extension" method for which other
errors get trapped. Look also for SystemError when running build_ext.run
method to check for this.
=> Added SystemError as possible compiling error

CHANGES, markupsafe/_native.py, markupsafe/_speedups.c, tests.py
This patch fixes the return type of `escape` to always be a `Markup`. It
addresses the issue with custom class that implements the `__html__`
method - see issue #68. A new test case, `test_escape_return_type`, is
added to test the behavior.
=> Fix the return type of escape to Markup

markupsafe/__init__.py, markupsafe/_speedups.c
From https://github.com/pallets/markupsafe/pull/15#issuecomment-21758817:
> JFTR: 2.5 support is not necessary, if it's still in the library it can be dropped.
=> Remove Python <= 2.5 code

appveyor.yml
This adds Appveyor CI for building Windows wheels. 
+ PyPy is *not* built because Appveyor doesn't come with PyPy pre-installed and I didn't want to figure out how to add it.
+ A stub for releasing to GitHub is included but commented out, as it will require the repo maintainer to generate a token and then secure it in Appveyor.
+ Wheel artifacts are made for every build and uploaded to Appveyor. It's out of scope of this PR to auto-upload them to PyPI.
+ Addresses #45, though I'm not sure if this PR actually closes it.
=> Add Appveyor script for building Windows wheels

tox.ini
the issue is that `python -m pytest` messes up the pythonpath and the coverage runnign uses it
unfortunately its not yet clear if pytest-cov has the same coverage results
=> [WIP] fix #94 by using pytest-cov instead of plain coverage

markupsafe/__init__.py, markupsafe/_compat.py
In Python 3.7, importing ABCs directly from the `collections` module shows a
warning (and in Python 3.8 it will stop working) - see
https://github.com/python/cpython/commit/c66f9f8d3909f588c251957d499599a1680e2320
This fixes the following `DeprecationWarning`:
```
>>> import warnings
>>> warnings.simplefilter('default')
>>> import markupsafe
.../markupsafe/__init__.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Mapping
```
=> Import Mapping from collections.abc

src/markupsafe/__init__.py
👋,
I was looking through this package and noticed some unreachable code that looks like it was missed when python 2.5 support was dropped [here](https://github.com/pallets/markupsafe/commit/e50c2699fc3751a922578a9fc248c64b49b19baa#diff-d3c944407b2648f7a54c52916239d94fR202). 
Now I'm not totally sure this code is even needed still. It looks like the `EscapeFormatter` will check for and call it. If it is still needed then perhaps a test is in order.
=> restore __html_format__ method

.appveyor.yml, .travis.yml, setup.cfg, src/markupsafe/__init__.py
Build wheels using [cibuildwheel](https://github.com/joerick/cibuildwheel) on Travis for Linux and Mac, and directly on Appveyor for Windows. Files are uploaded to S3 on my AWS account for now.
Closes #45
=> Build wheels

src/markupsafe/_speedups.c, tests/test_exception_custom_html.py
If the method raises an exception, PyObject_CallObject() returns NULL,
but the code didn't check for that, which led to a segfault.
Fixes #108
=> Add NULL check after native call to __html__ method

.travis.yml
Travis CI has deprecated the `sudo:` tag.
=> Travis CI: Add Python 3.8 and the current pypy3

.azure-pipelines.yml
See joerick/cibuildwheel#254. Building the wheel for Python 3.5 on Windows was having some trouble with the compiler, switching to an older image fixed it.
=> use older Windows image for building Python 3.5

src/markupsafe/__init__.py
This was only needed to enable empty and mixed positional formatting in Python < 3.5.
=> remove format spec mapping helper

.github/workflows/build.yaml
From v1.8.0, cibuildwheel allows for building non-native architectures with the CIBW_ARCHS_LINUX option.
See https://cibuildwheel.readthedocs.io/en/stable/options/#archs for more details.
=> Build aarch64 wheels

setup.py
The C extension is twice as slow as the native code on PyPy. Maybe this can be re-evaluated later.
closes #176
=> don't build speedups on PyPy with cibuildwheel

.github/workflows/build.yaml, setup.cfg, setup.py
Use py_limited_api to build one wheel for 3.6+. Currently testing this.
Use cibuildwheel as a GitHub action. Don't need `setup-python` or `pip install`.
Build a MacOS universal2 wheel. From what I could tell from the cibuildwheel docs, this seems to be preferred over building the arm64 wheel.
closes #175
=> build py_limited_api abi3 wheel and MacOS universal2 wheel

.github/workflows/build.yaml, setup.cfg, setup.py
MarkupSafe uses the Python Unicode API, which is mostly unavailable with `Py_LIMITED_API`.  I don't have the expertise to rewrite the C to be compatible with the limited API, so I'll continue to build version wheels for now. While it would be nice to build fewer wheels with abi3, it's not particularly a problem for me to push a new CI config then upload the new wheels when a new Python version is available.
closes #175
=> remove abi3 limited api builds

src/markupsafe/__init__.py
Noticed this while adding types to Jinja. `EscapeFormatter` should call `super().__init__()`. It doesn't affect anything, but is more correct for subclassing hierarchies.
Also, `EscapeFormatter`, and `_MarkupEscapeHelper` can use slots to avoid some overhead. This is more useful for the the helper class, which may be created many times when doing `Markup % args`. `Markup` already uses slots.
=> call string.Formatter.__init__

.github/workflows/build.yaml
- Update cibuildwheel to 1.11.0.
- cibuildwheel 1.9.0 automatically skips versions based on `python_requires`.
=> cibuildwheel skips based on python_requires

CHANGES.rst, src/markupsafe/__init__.py, tests/test_markupsafe.py
In the scenario of a missing single placeholder, the mod operator did
not fail as it does when having multiple placeholder
```py
>>> Markup("foo") % 42
Markup("foo")
>>> Markup("foo") % (42, 43)
TypeError: not all arguments converted during string formatting
>>> Markup("foo") % (42,)
TypeError: not all arguments converted during string formatting
```
This commits unifies the behaviour with the mod operator on native
strings and fails in the three above scenario
- fixes #225
Checklist:
=> raise error upon missing placeholder

CHANGES.rst, src/markupsafe/__init__.py, src/markupsafe/_native.py, src/markupsafe/_speedups.c, tests/conftest.py, tests/test_markupsafe.py
Removed:
* `soft_unicode`, use `soft_str` instead
=> remove deprecated code

CHANGES.rst, src/markupsafe/__init__.py, tests/test_markupsafe.py
Split up regex used by `striptags` to handle comments before tags. This avoids ambiguous regex matches which could lead to backtracking.
=> avoid ambiguous regex in striptags

CHANGES.rst, src/markupsafe/__init__.py, tests/test_markupsafe.py
=> Match newlines when stripping tags

CHANGES.rst, src/markupsafe/__init__.py, tests/test_markupsafe.py
`format_map` was missing, meaning the format arguments would not be escaped when using it. `casefold`, `removeprefix`, and `removesuffix` were missing, meaning they'd return `str` instead of `Markup`. The `remove...` methods are only in Python >= 3.9.
fixes #370
=> implement missing `str` methods

CHANGES.rst, src/markupsafe/__init__.py
Following up on #377, @Daverball pointed out that using `Self` would be more correct.
=> use `Self` for return type annotation

.github/workflows/tests.yaml, .pre-commit-config.yaml, CHANGES.rst, pyproject.toml, tox.ini
[Python 3.7 reached end of life on 2023-07-27.](https://endoflife.date/python)
=> drop support for Python 3.7

CHANGES.rst, setup.py
`distutils` is removed in Python 3.12. `setuptools` provides a patch that keeps `distutils` imports working, but also re-exports the names from `setuptools`.
=> import from setuptools instead of distutils

CHANGES.rst, pyproject.toml, src/markupsafe/__init__.py
The `__version__` attribute is an old pattern from early in Python packaging. Setuptools eventually made it easier to use the pattern by allowing reading the value from the attribute at build time, and some other build backends have done the same.
However, there's no reason to expose this directly in code anymore. It's usually easier to use feature detection (`hasattr`, `try/except`) instead. `importlib.metadata.version("markupsafe")` can be used to get the version at runtime in a standard way, if it's really needed.
---
Also, given some of the changes going into the next version, 3.0 feels more appropriate than 2.2.
=> deprecate `__version__` attribute

CHANGES.rst, src/markupsafe/__init__.py, tox.ini
The regular expression method of finding anything between comment or tag marks can be slow on large input, especially if it doesn't contain an end mark. Instead, use some simple `str.find` calls to incrementally remove blocks. The code can be cleaned up in `main` by using `:=` assignment expressions.
=> improve striptags performance

CHANGES.rst, src/markupsafe/__init__.py, tests/test_markupsafe.py
This PR restores order of operations in Markup.striptags.
Prior to 2.1.4, the order of operations in striptags was:
1. strip comments
2. strip tags
3. coalesce whitespace
In 2.1.4 the order changed to:
1. coalesce whitespace
2. strip comments
3. strip tags
As a result extra spaces were introduced in the output in cases where whitespace was separated from more whitespace by a tag or comment.
- fixes #417
Checklist:
- [n/a] Add or update relevant docs, in the docs folder and in code.
- [n/a] Add `.. versionchanged::` entries in any relevant code docs.
=> Fix for spurious whitespace in striptags output

src/markupsafe/__init__.py
There is a copy/paste error in the code that creates __version__ to the wrong package.
=> Fix error in __version__

CHANGES.rst, src/markupsafe/_speedups.c
This PR reduces the overall call time to `escape()` by about 40% when the input is a string by not calling `PyObject_GetAttr()` _unless_ it isn't a unicode object.
`PyObject_GetAttr` is one of the most expensive calls in the C-API, compared with `PyUnicode_CheckExact` which is an interned pointer comparison (very fast).
Before: 
After:
=> Skip costly attribute check for unicode strings

.github/workflows/tests.yaml, CHANGES.rst, pyproject.toml, src/markupsafe/__init__.py, tox.ini
It goes end of life this month, presumably tomorrow when 3.13 is released. https://devguide.python.org/versions/#supported-versions
=> drop support for python 3.8

.github/workflows/publish.yaml, .github/workflows/tests.yaml, CHANGES.rst, src/markupsafe/_speedups.c, tests/conftest.py, tox.ini
Python 3.13 RC1 was released recently[^1]:
<blockquote>
We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc1 will work with future versions of Python 3.13. As always, report any issues to [the Python bug tracker ](https://github.com/python/cpython/issues).
</blockquote>
It'd be really nice to have wheels to start testing applications that use MarkupSafe before the eventual final release.
Thanks!
~PS: This PR is only for GIL-enabled 3.13 wheels and not free-threaded ones[^2], which will certainly involve a higher level of effort.~
[^1]: …
=> Build Python 3.13 wheels

CHANGES.rst, pyproject.toml, src/markupsafe/_speedups.c, tests/test_escape.py
`__str__` should return a `str`, but could return a subclass of `str` instead. Relax the C check from `PyUnicode_CheckExact` (exact type) to `PyUnicode_Check` (subclass). This will still fail if `__str__` returns a non-string, but at that point I'm calling it a bug in the code that does that.
fixes #472 
Also added a test for #467.
=> relax speedups str check

CHANGES.rst, pyproject.toml
Setuptools 70.1 builds wheels directly instead of needing the wheel package.
fixes #475
=> build requires at least setuptools 70.1

CHANGES.rst, src/markupsafe/_speedups.c, tests/test_ext_init.py
Per #494, this PR effects multi-phase init for MarkupSafe.
I've also added a test to ensure things are working properly.
Thanks,
Adam
=> Adopt multi-phase initialisation (PEP 489)

.github/workflows/tests.yaml, CHANGES.rst, pyproject.toml, uv.lock
https://palletsprojects.com/versions
> When a release is made, it supports all Python versions that are not within six months of end of life (EOL). See [Python's EOL calendar](https://devguide.python.org/versions/) for timing.
=> drop end of life python versions

CHANGES.rst, src/markupsafe/__init__.py
- `__version__`, use feature detection or `importlib.metadata.version` instead
=> remove previously deprecated code

.github/workflows/tests.yaml, pyproject.toml, tests/test_ext_init.py, tests/test_leak.py, uv.lock
Mark the project as compatible with free-threading.
Stress-test the whole test suite (and, crucially, `_speedups.so`) by running it in parallel over multiple threads.
This aims to detect race conditions where functions may share a thread-unsafe global state.
Namely, in the future one may add a global cache, which carries thread-safety concerns.
=> Free-threading: run with pytest-run-paralell
